services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: passadmin
    volumes:
      - ./data:/data                 
      - ./config:/root/.minio        
    command: server /data --console-address ":9001"